compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
main_training_function: main
mixed_precision: bf16

machine_rank: 0
main_process_ip: 10.128.0.14
main_process_port: 6969

num_machines: 8
num_processes: 64

rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
